name = "allyshipglobal"
compatibility_date = "2024-03-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "allyshipglobal"
database_id = "your-database-id"

[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"

[[custom_domains]]
domain = "allyshipglobal.com"
zone_id = "your-zone-id"

[build]
command = "npm run pages:build"

[site]
bucket = ".vercel/output/static"

[build.environment]
NODE_VERSION = "20"
NPM_VERSION = "10"
NEXT_PUBLIC_SITE_URL = "https://allyshipglobal.com"

# Enable Node.js compatibility
node_compat = true

[[build.upload]]
type = "sites"
dir = ".vercel/output/static"
include = ["**/*"]
exclude = []

[env.production]
node_compat = true

# Custom domains configuration
[[routes]]
pattern = "allyshipglobal.com"
custom_domain = true

[[routes]]
pattern = "www.allyshipglobal.com"
custom_domain = true 