name = "allyship-global"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run pages:build"
pages_build_output_dir = ".vercel/output/static"

[site]
bucket = ".vercel/output/static"

[build.environment]
NODE_VERSION = "20"
NPM_VERSION = "10"

# Enable Node.js compatibility
node_compat = true

[[build.upload]]
type = "sites"
dir = ".vercel/output/static"
include = ["**/*"]
exclude = []

[env.production]
node_compat = true 