[build]
command = "npm run pages:build"
publish = ".vercel/output/static"

[build.environment]
NODE_VERSION = "20"
NPM_VERSION = "10"
NEXT_PUBLIC_BASE_PATH = ""
NEXT_PUBLIC_SITE_URL = "https://allyshipglobal.com"
NODE_ENV = "production"
NODE_COMPAT = "true"

[functions]
node_compat = true
compatibility_flags = ["nodejs_compat"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.processing]
skip_processing = false

[build.processing.html]
pretty_urls = true

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

[build.processing.images]
compress = true

[compatibility]
nodejs_compat = true

[site]
bucket = ".vercel/output/static"

[site.domains]
main = "allyshipglobal.com"
www = "www.allyshipglobal.com" 