[build]
command = "npx @cloudflare/next-on-pages@1"
publish = ".vercel/output/static"

[build.environment]
NODE_VERSION = "20"
NPM_VERSION = "10"
NEXT_PUBLIC_BASE_PATH = ""
NODE_ENV = "production"

[functions]
node_compat = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.processing]
skip_processing = false

[build.processing.html]
pretty_urls = true

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

[build.processing.images]
compress = true 