'use client'

import {
  type LucideIcon,
  Twitter,
  Github,
  Linkedin,
  Mail,
  MapPin,
  Phone,
  Building,
  Handshake,
  BarChart,
  Ship,
  Cpu,
  Zap,
  Image,
  ChevronDown,
  ChevronUp,
  Clock,
  Shield,
  User,
  Layout,
  Target,
  Newspaper,
  Lightbulb,
  GraduationCap,
  Map,
  ArrowRight,
  Menu,
  X,
  Home,
  Users,
  Briefcase,
  Cloud,
  DollarSign,
  Globe,
  Star,
  FileText,
  Route,
  Droplet,
  TrendingUp,
  Activity,
} from 'lucide-react'

interface IconsType {
  [key: string]: LucideIcon
}

export const Icons: IconsType = {
  twitter: Twitter,
  github: Github,
  linkedin: Linkedin,
  mail: Mail,
  mapPin: MapPin,
  phone: Phone,
  building: Building,
  handshake: Handshake,
  chartBar: BarChart,
  ship: Ship,
  cpu: Cpu,
  zap: Zap,
  image: Image,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  clock: Clock,
  shield: Shield,
  user: User,
  layout: Layout,
  target: Target,
  newspaper: Newspaper,
  lightbulb: Lightbulb,
  graduationCap: GraduationCap,
  map: Map,
  arrowRight: ArrowRight,
  menu: Menu,
  x: X,
  home: Home,
  users: Users,
  briefcase: Briefcase,
  cloud: Cloud,
  dollarSign: DollarSign,
  globe: Globe,
  star: Star,
  fileText: FileText,
  route: Route,
  droplet: Droplet,
  trendingUp: TrendingUp,
  activity: Activity,
} 